remove erroneous source: options in has_many
The `source` option is documented as follows:

> Specifies the source association name used by `#has_many :through`
> queries. Only use it if the name cannot be inferred from the
> association. `has_many :subscribers, through: :subscriptions` will
> look for either `:subscribers` or `:subscriber` on `Subscription`,
> unless a `:source` is given.

Therefore it's not needed here, and it actually breaks `rake
db:setup`:

```
Parties selected for GE
rake aborted!
ArgumentError: Unknown key: :source. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :autosave, :before_add, :after_add, :before_remove, :after_remove, :extend, :counter_cache, :join_table, :index_errors, :ensuring_owner_was
```